theme: minima
title: "GeoSocket.io"
tagline: "Geo location with social integration"
description: "Free and ethic geo-location based services for humanity"
url: "https://docs.geosocket.io"
locale: "en_US"
google_analytics: "G-TJ9QB4YRSZ"
header_pages:
  - about.md
minima:
  date_format: "%b %-d, %Y"
twitter_username: geosocket-io
github_username:  geosocket-io
twitter:
  username: geosocket-io
  card: summary
